[package]
name = "ckb-vm-rs-tests"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "is13-runtime"
path = "is13-runtime.rs"

[dependencies]
ckb-vm = { path = "../ckb-vm" }
b_error = { path = "../bloop/src/error" }
bytes = "0.4.12"
